//============================================================================================================================
//== //LIST ALL//  ==========  List All Books  ===============================================================================
//============================================================================================================================
GET http://localhost:8080/books

###

//============================================================================================================================
//==  //ADD//  ======= Add the Book Specified Below to the Database ==========================================================
//============================================================================================================================
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "author": "J.R.R.Tolkien",
  "type": "High Fantasy Roman",
  "publisher": "JRRTolkien Foundation",
  "isbn": 5088822855
  }

###

//============================================================================================================================
//==  //LIST ONE//  ====================  Display the Book with the ID at the End of the URL  ================================
//============================================================================================================================
GET http://localhost:8080/books/5

###


//============================================================================================================================
//==  //EDIT//  ====  Override the Book with the ID Specified at the End of the URL with the Book Specified Below  ===========
//============================================================================================================================
PUT http://localhost:8080/books/3
Content-Type: application/json

{
  "title": "Hensel un Gretel",
  "author": "Maria Meier-Müller",
  "type": "Children's book",
  "publisher": "Springer",
  "isbn": 439723683752
}

###


//============================================================================================================================
//===  //DELETE//  ===================== Delete the Book with the ID Specified at the End of the URL  ========================
//============================================================================================================================
DELETE http://localhost:8080/books/1

###

