GET http://localhost:8080/books

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "LOTR",
  "author": "Gabriel",
  "type": "Roman",
  "publisher": "Martin",
  "isbn": 50
  }

###

GET http://localhost:8080/books/1

###

PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "LOTR",
  "author": "Hans",
  "type": "Roman",
  "publisher": "Martin",
  "isbn": 50
}

###

DELETE http://localhost:8080/books/1

###

