http://localhost:8080/books

###

POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "LOTR",
  "author": "Gabriel",
  "type": "Roman",
  "publisher": "Martin",
  "isbn": 50
  }

###
